---
galaxy_info:
  author: Hector Castro
  description: An Ansible role for installing Terraform.
  company: Azavea Inc.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - cloud
  - system
dependencies:
  - src: azavea.unzip
    version: 0.1.2
    name: azavea.unzip
